### ISSUE TITLE
Add slot "has_training_resource"

### ISSUE THREAD

**Issue by katiestahl** [bridge2ai/b2ai-standards-registry#129]
See comments [here](https://docs.google.com/spreadsheets/d/1IeOj5S9tYGrHVIH15QWzxUNbBWKxMUnwrIj0ELO-8Xk/edit?disco=AAABWWMoWLE)

Add a new slot called `has_training_resource` to the `DataStandardOrTool` table to link standards/tools to their supporting training resources/guides/etc. The currently available training resources are denoted by having `TrainingProgram` in their `category`. Find the standards they apply to and link them with the new slot.

**Comment by caufieldjh** [comment]
Completed in https://github.com/bridge2ai/standards-schemas/pull/39
